### ISSUE TITLE
NameError: uninitialized constant Adp::Connection::UserInfoHelper

### ISSUE THREAD

**Issue by anatoljevich** [adplabs/adp-connection-ruby#16]
I'm getting name error when trying to run example code in rails.

    clientcredential_config = Adp::Connection::ClientCredentialConfiguration.new(config);
    connection = Adp::Connection::ApiConnectionFactory::createConnection(clientcredential_config)
    connection.connect();
    helper = Adp::Connection::UserInfoHelper.new(connection)

I don't see any UserInfoHelper class in the library, so I'm not sure how it is supposed to work.

**Comment by ADPMarketplacePHP** [comment]
Our RUBY example also requires the adp-userinfo-ruby project for the demo to run.  See this page:  https://github.com/adplabs/adp-userinfo-ruby

**Comment by anatoljevich** [comment]
Got it. Thanks.

**Comment by ADPMarketplace** [comment]
Thank you for letting us know.
