### ISSUE TITLE
Use of Log

### ISSUE THREAD

**Issue by arashb31** [adplabs/adp-connection-ruby#17]
The library seems to throw errors unless the constant "Log" is defined.
The library seems tightly coupled to this requirements, and this seems unnecessary.

If the library throws an exception, sometimes we get this error:
NameError: uninitialized constant Adp::Connection::AuthorizationCodeConnection::Log

Probably would be better to specify the Logger on the ADP class, such as ADP.logger = Logger.new("STDOUT") and internally use that logger, rather than have explicit calls to "Log.debug"

**Comment by ADPMarketplacePHP** [comment]
Hello,

We're aware of this.  In the meantime, this issue has been raised and that thread has a workaround for your to use until the next version of the library is released.

https://github.com/adplabs/adp-connection-ruby/issues/15

**Comment by arashb31** [comment]
Great thanks. I fixed it by monkey-patching.

Adp::Log = Logger.new("STDOUT")

**Comment by ADPMarketplacePHP** [comment]
Thank you, glad you got it working.

**Comment by ADPMarketplace** [comment]
This request was closed and merged into request #134823 "Use of Log".

**Comment by ADPMarketplace** [comment]
Request #134822 "Use of Log" was closed and merged into this request. Last comment in request #134822:

URL: https://github.com/adplabs/adp-connection-ruby/issues/17

User Login: arashb31

The library seems to throw errors unless the constant "Log" is defined.
The library seems tightly coupled to this requirements, and unnecessarily.

If the library throws an exception, sometimes we get this error:
NameError: uninitialized constant Adp::Connection::AuthorizationCodeConnection::Log
