### ISSUE TITLE
Calling ADP API's

### ISSUE THREAD

**Issue by arashb31** [adplabs/adp-connection-ruby#18]
How do we actually call the ADP API's once we have a ADP Clients oauth2 token?
For example, how would we call the /hr/v2/worker-demographics ?

**Comment by ADPMarketplace** [comment]
Hi Arash,

After you obtain a oauth2 token you need to make feature call using that bearer(oauth2 token) in the headers of the API call.
Please refer to the screenshot to make /hr/v2/worker-demographics API call.

Thanks,
Sahithi Reddy

**Comment by Sahithi066** [comment]
![image](https://user-images.githubusercontent.com/47520525/52559739-25d21e00-2e1c-11e9-9a15-bb23596ff485.png)

**Comment by arashb31** [comment]
Does this library let you actually make any calls to the API once we get the token back?
Is there a method to make the call?
Pseudo-code:

api = AdpApi.new(bearer_token)
api.get('/hr/v2/worker-demographics')

Does it support anything like that? Or would we need to create our own client?

**Comment by ADPMarketplace** [comment]
Hi Aarsh,
There are 2 types of applications:
    1) End-User Application
    2) Data Connector Application

You can use any one of the application type to make the API calls. There are 2 calls you'd be making
    1) Token call
    2) Feature call

In Token call, you'd be passing client ID and secret and getting token as a response.
In feature call, you'd need to pass the token and get the actual records.
For more information please go through the following link.
https://developers.adp.com/articles/guides/build-dataConn-app-w-dev-lib-Ruby

Thanks,
Sahithi Reddy

**Comment by arashb31** [comment]
Hi Sahithi, 

Thanks for the reply. How do you do the actual "feature call"? Where is sample code showing how to make those calls? All it shows is 
```
connection.connect();
session["ClientCredential"] = connection;

```
But where is the code, for example, calling /hr/v2/worker-demographics ?

**Comment by ADPMarketplace** [comment]
Hi Aarsh,

You will be getting access token from the below code.

connection.connect();
session["ClientCredential"] = connection;

---

Now please refer to the below sample code where you need to replace the <Token> value with the one you just got as part of above call. Please make sure to bypass any firewall\proxy while making the call. The response object will have the response of the "/hr/v2/worker-demographics" API. If the below code fails to work in your system, please make sure to use valid host and port number in place of 'host' and 'port' fields.

Sample code to make feature call:
-------

require 'uri'
require 'net/http'

url = URI("https://api.adp.com/hr/v2/worker-demographics")

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Get.new(url)
request["authorization"] = 'Bearer <Token>'

response = http.request(request)
puts response.read_body

Thanks,
Mahesh
