### ISSUE TITLE
OpenSSL::SSL::SSLError at /client_credentials/login SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed file: http.rb location: connect line: 920

### ISSUE THREAD

**Issue by philrosenstein** [adplabs/adp-connection-ruby#2]
I cloned the repo and followed instructions to get demo client up and running locally.  Sinatra app starts up and everything looks fine until I click login expecting to provide the demo credentials, and this error happens:

OpenSSL::SSL::SSLError at /client_credentials/login
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
file: http.rb location: connect line: 920

Looks like an issue with SSL cert from ADP end?  Any ideas?

**Comment by philrosenstein** [comment]
seems to be working after doing this on my mac:

$ brew tap raggi/ale
$ brew install openssl-osx-ca

as suggested here http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by philrosenstein** [comment]
getting it again when trying to get_token 

D, [2016-04-06T14:24:11.868907 #5753] DEBUG -- : connection configutration: #<Adp::Connection::AuthorizationCodeConfiguration:0x007fea12e9ad78 @clientID="ec762f06-7410-4f6d-aa82-969902c1836a", @clientSecret="6daf2cd7-4604-46c0-ab43-a645a6571d34", @sslCertPath="config/certs/apiclient_iat.pem", @sslKeyPath="config/certs/apiclient_iat.key", @sslKeyPass="adpadp10", @tokenServerURL="https://iat-api.adp.com/auth/oauth/v2/token", @apiRequestURL="https://iat-api.adp.com", @accessScope="hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read,", @authorizationCode="c5cc44b5-a51a-4019-a5bf-7e97f2f021e3", @baseAuthorizationURL="https://iat-accounts.adp.com/auth/oauth/v2/authorize", @redirectURL="http://localhost:8889/callback", @responseType="code", @scope="openid", @state=nil, @grantType="authorization_code">
D, [2016-04-06T14:24:11.869027 #5753] DEBUG -- : URL: https://iat-api.adp.com/auth/oauth/v2/token
D, [2016-04-06T14:24:11.869067 #5753] DEBUG -- : Client ID: ec762f06-7410-4f6d-aa82-969902c1836a
D, [2016-04-06T14:24:11.869090 #5753] DEBUG -- : Client Secret: 6daf2cd7-4604-46c0-ab43-a645a6571d34
D, [2016-04-06T14:24:11.869111 #5753] DEBUG -- : Grant Type: authorization_code
2016-04-06 14:24:13 - OpenSSL::SSL::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed:
	/Users/phil/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:920:in `connect'

**Comment by ADPMarketplace** [comment]
We have uploaded the ADP CA Certificate to the adp-connection-ruby client library (https://github.com/adplabs/adp-connection-ruby/tree/master/democlient/config/certs) that you can import into your keychain.

Thanks.

**Comment by philrosenstein** [comment]
Thanks, I've sent you a pull request to load that certificate into the connection's certificate store.. https://github.com/adplabs/adp-connection-ruby/pull/3

**Comment by MichaelBowers** [comment]
Apologies for leaving this dangling for so long - I've merged in your changes.
