### ISSUE TITLE
Missing variable declaration in api_connection.rb, resulting in ERROR

### ISSUE THREAD

**Issue by cpkenn09y** [adplabs/adp-connection-ruby#4]
The "Adp::Connection::ApiConnection" module has four log statements that throw an error when used in a Rails application - resulting an a complete stop of execution.

```
Log.debug("URL: #{url}")
Log.debug("Client ID: #{data["client_id"]}")
Log.debug("Client Secret: #{data["client_secret"]}")
Log.debug("Grant Type: #{data["grant_type"]}")
```

Following the pattern in your README example, we added the following lines into our codebase:

```
config = YAML.load_file('config/adp_credentials.yml')
clientcredential_config = Adp::Connection::ClientCredentialConfiguration.new(config)
connection = Adp::Connection::ApiConnectionFactory::createConnection(clientcredential_config)
access_token = connection.connect()
```

The above code, leads to the following error.
![screenshot 2016-05-02 10 55 34](https://cloud.githubusercontent.com/assets/5041660/14962636/b139f00a-1054-11e6-9893-d7d847c0a7ce.png)

** The file api_connection.rb is missing a variable declaration for _Log_. As a result, applications will throw an error

Note: naming the variable **Log** with a capital letter breaks standard Ruby/Rails naming conventions and will throw a _dynamic constant assignment error_ (see the following error). The variable should be named **log**

![screenshot 2016-05-02 11 15 03](https://cloud.githubusercontent.com/assets/5041660/14963445/84d6465e-1058-11e6-8479-34d61876c37f.png)

### I strongly recommend that you use the following code:
![screenshot 2016-05-02 11 20 04](https://cloud.githubusercontent.com/assets/5041660/14963311/dc339524-1057-11e6-8a48-2dd6c23cf7a1.png)

** This will allow the gem to run in any Ruby/Sinatra/Rails context

**Comment by cpkenn09y** [comment]
please fix asap, we are trying to use your gem for our ADP integration. we will be escalating this issue with our ADP point of contact as well. thanks

**Comment by cpkenn09y** [comment]
many thanks for the quick resolution!

**Comment by cpkenn09y** [comment]
was a new build of the gem pushed out? I did a bundle install & it did not pick up a new version.

**Comment by cpkenn09y** [comment]
verified that the new build still needs to get pushed out to rubygems. The last build that was pushed out was on Mar. 8, 2016. Thanks for your help with this

![screenshot 2016-05-04 08 35 58](https://cloud.githubusercontent.com/assets/5041660/15019578/787f6ec2-11d3-11e6-98ab-f03cc5084ddc.png)

**Comment by ADPMarketplace** [comment]
The latest version of the Gem has been uploaded as 0.1.2.

**Comment by cpkenn09y** [comment]
many thanks for the updates & very quick resolution. I have verified the ability to pull the new gem version and that the access token retrieval now works without throwing the aforementioned errors. 

closing this issue. thanks!
