### ISSUE TITLE
Support strings for all configuration options that currently require a file path

### ISSUE THREAD

**Issue by rhec** [adplabs/adp-connection-ruby#6]
In some production environments, the best practice is to store credentials in environment variables, rather than the filesystem. Since in this case the file path just gets opened and read into a string, this should be a pretty simple fix.

Specifically, the config options
- sslCertPath
- sslKeyPath
- sslCaPath (if #3 is merged)

Should have companion config options which accept strings instead of paths
- sslCert
- sslKey
- sslCa

**Comment by ADPMarketplace** [comment]
Thanks for your feedback. Please feel free to update the Ruby Developer Library and issue a pull request that we can incorporate back into the library.

Thanks.

**Comment by rhec** [comment]
@ADPMarketplace no problem. Can you merge #3 first since it introduces another file path, so that I can do a single PR?

**Comment by MichaelBowers** [comment]
I've merged in the outstanding pull request so that you can submit yours.  Thanks!
