### ISSUE TITLE
Issue with SSLCaPath

### ISSUE THREAD

**Issue by gavyjatt** [adplabs/adp-connection-ruby#9]
Hi, I was working with the Ruby Demo and I ran the demo and it worked but i could not locate the following in my key/pem combination provided by ADP 

sslCaPath:             config/certs/apiclient_iat_chain.pem

I have tried to comment out and got the error which says the following

OpenSSL::X509::StoreError at /authorization_code/get_token

![image](https://cloud.githubusercontent.com/assets/6989660/23666287/3403457c-0320-11e7-9964-b733e6b98292.png)

and in my case i do not have the iat_chain.pem file because i do not know where it is coming from and in the adp documentation, they have provided no relevance to it, that is it is a part of the pem, key or not 

even there is another small glitch which is the sslkeypass: that is something which i think is not required when you have the key adn pem files only, but if you create any pfx file, that could be part of it, even the same scenario used in the demo but no reference of the same 

SSLKeyPass and SSLCaPath in the adp Website Documentation (marketplace)

**Comment by ADPMarketplace** [comment]
The signed certificate that you received from ADP includes the certificate in the email body. Copy and paste your signed certificate into a new text file, including the -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- lines. Save the file with a .pem extension.

After this is done, change the following two lines in both authorizationcode_config.yml and clientcredential_config.yml:

sslCertPath: [path to the *.pem file] 
sslKeyPath: [path to the *.key file used to generate the CSR]

democlient should now work using your certificate.

**Comment by inveterateliterate** [comment]
I have the same issue. I have no idea what file to reference for the `sslCaPath`.

I have no issues though If I comment out the following:

```
http.cert_store = OpenSSL::X509::Store.new
http.cert_store.add_file(self.connection_configuration.sslCaPath)
```

The demo client runs successfully as well with those lines commented out. Can these lines be removed especially now that the certificates have been updated?  (https://github.com/adplabs/adp-connection-ruby/commit/e91232ec0dc6431a6b7d59b05bd32e63675a20d3)
